spring.application.name=export-user
server.port=8081

spring.datasource.url=${DB_USER_URL:jdbc:postgresql://localhost:5432/reliab_user}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

feign.client.config.organization-service.url=${ORGANIZATION_SERVICE_URL:http://localhost:8082}
feign.circuitbreaker.enabled=true
spring.cloud.compatibility-verifier.enabled=false
